// Code generated by hertz generator.

package main

import (
	handler "douyin/api_gateway/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
	"douyin/middleware"

)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", middleware.JWTMiddleware(),handler.Ping)

	// your code ...

	
	rg := r.Group("/douyin")
	{
		userGroup := rg.Group("/user")
		{
			userGroup.POST("/register/",  handler.UserImplInst.Register)
			userGroup.POST("/login/",  handler.UserImplInst.LogIn)
			userGroup.GET("/", middleware.JWTMiddleware(),handler.UserImplInst.GetUserById)
		}

		feedGroup := rg.Group("/feed")
		{
			feedGroup.GET("/",handler.FeedImplInst.GetFeed)
		}

	}

	
}
